version: "3.0"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  cisco_router:
    image: snmp_simulator:latest
    networks:
      - back-tier
    volumes:
      - ./snmp_simulator/data/snmpwalk_cisco_c2801:/app/snmpwalk
    restart: always
  palo_alto:
    image: snmp_simulator:latest
    networks:
      - back-tier
    volumes:
      - ./snmp_simulator/data/snmpwalk_paloalto:/app/snmpwalk
    restart: always
  telegraf:
    image: telegraf:latest
    restart: always
    container_name: telegraf
    hostname: telegraf
    networks:
      - back-tier
    volumes:
      - ./telegraf/mibs/:/usr/share/snmp/mibs/
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - 9126:9126
    command: telegraf --config /etc/telegraf/telegraf.conf
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - back-tier
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - back-tier
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    networks:
      - back-tier
      - front-tier
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
