version: "3.0"

services:
  router:
    build:
      context: ./snmp_server
    restart: always

  telegraf:
    image: telegraf:latest
    restart: always
    container_name: telegraf
    volumes:
      - ./telegraf/mibs/:/usr/share/snmp/mibs/
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - 9126:9126
    command: telegraf --config /etc/telegraf/telegraf.conf

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana/"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
