global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  #   # - "second.rules"
  #
scrape_configs:
  - job_name: telegraf
    static_configs:
      - targets: ["telegraf:9126"]
